# Transposing Array

In [46]:
import numpy as np

mat1 = np.arange(6).reshape(2,3)
print(mat1)
print(np.transpose(mat1), '\n**************')

mat2 = np.arange(24).reshape(2,3,4)
print(mat2)
print(f'The shape of mat2: {mat2.shape}')
print(mat2.transpose())
print(np.transpose(mat2))
print(np.transpose(mat2) == mat2.transpose())
print(f'The shape of transposed mat2 is: {np.transpose(mat2).shape}', '\n**************')

print(f'The mat2 transposed in (2,0,1):\n {mat2.transpose((2,0,1))}')

print(f'Swape the axis: \n{mat2.swapaxes(0,2)}')
print(mat2.swapaxes(0,2) == mat2.transpose(2,1,0))

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]] 
**************
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
The shape of mat2: (2, 3, 4)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
[[[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]
  [ True  True]]]
The shape of transposed mat2 is: (4, 3, 2) 
**************
The mat2 transposed in (2,0,1):
 [[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
Swape the axis: 
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
[[[ True 

# Stacking Arrays

In [40]:
m1 = np.full((2,3), 1)
m2 = np.full((2,3), 2)

print(m1)
print(m2, '\n')

print(f'h, m1, m1: \n {np.hstack((m1,m1))}')
print(f'h, m1, m2: \n {np.hstack((m1,m2))}')
print(f'h, m2, m1: \n {np.hstack((m2,m1))}')
print(f'v, m1, m2: \n {np.vstack((m1,m2))}')

[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]] 

h, m1, m1: 
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]]
h, m1, m2: 
 [[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
h, m2, m1: 
 [[2 2 2 1 1 1]
 [2 2 2 1 1 1]]
v, m2, m1: 
 [[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


In [57]:
print(np.stack((m1,m2)))

[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]]


In [44]:
print(f'concatenate 0: \n {np.concatenate((m1,m2), 0)}')
print(f'concatenate 1: \n {np.concatenate((m1,m2), 1)}')

concatenate 0: 
 [[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
concatenate 1: 
 [[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [66]:
mat = np.eye(3)
print(mat)
print(f"Tile mat for 3 times in row: \n {np.tile(mat, (3,1))}")
print(f"Tile mat for 9 times, 3 in row and 3 in column: \n {np.tile(mat, (3,3))}")
print(f"Tile mat for 6 times, 3 in row and 2 in column: \n {np.tile(mat, (3,2))}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Tile mat for 3 times in row: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Tile mat for 9 times, 3 in row and 3 in column: 
 [[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]
Tile mat for 6 times, 3 in row and 2 in column: 
 [[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]


# Splitting Array

In [56]:
big_mat = np.arange(36).reshape(9,4)

print(big_mat, '\n')

sp1, sp2, sp3 = np.vsplit(big_mat,3)
print(f'vertical split: \n {sp1}, \n{sp2}, \n{sp3} \n')

sph1, sph2 = np.hsplit(big_mat, 2)
print(f'horizontal split: \n {sph1}, \n{sph2} \n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]] 

vertical split: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], 
[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]] 

horizontal split: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]
 [24 25]
 [28 29]
 [32 33]], 
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]
 [26 27]
 [30 31]
 [34 35]] 



# Broadcasting

## 规则1 
如果两个数组的维度不同，那么小维度数组的形状将会在最左边补1

In [81]:
mat = np.arange(5).reshape(1,1,5)
print(mat)
print(mat + [10,10,10,10,10])

mat = np.arange(6).reshape(2,3)
print(mat)
print(mat + [10,10,10])

[[[0 1 2 3 4]]]
[[[10 11 12 13 14]]]
[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [13 14 15]]


## 规则2
如果两个数组的形状不在任何一个维度上都匹配，那么数组的形状则会沿着维度相同的方向扩展，以匹配另一个数组的形状。

In [74]:
mat = np.arange(6).reshape(2,3)
print(mat)
print(mat + [[10],[20]])
print(mat + [[10,20,30]])
print(mat + 100)

[[0 1 2]
 [3 4 5]]
[[10 11 12]
 [23 24 25]]
[[10 21 32]
 [13 24 35]]
[[100 101 102]
 [103 104 105]]


## 规则3：
如果两个数组的形状在任何一个维度上都不匹配，并且没有任何一个维度为1，那么就会引起异常

In [76]:
try: 
    print(mat + [[10,20]])
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (1,2) 


## 规则4: upcasting
将不同数据类型的数组进行运算时，运算结果会自动将数据类型转变为更为精确的数据类型：

In [86]:
m1 = np.arange(5, dtype = np.int8)
m2 = np.arange(5,10, dtype = np.int16)
 
print(f'm1 datatype: {m1.dtype} \nm2 datatype: {m2.dtype} \nm1+m2 datatype: {(m1+m2).dtype}')

m1 datatype: int8 
m2 datatype: int16 
m1+m2 datatype: int16


# Exercise

In [99]:
m1 = np.arange(8).reshape(2, 4)
m2 = np.arange(8).reshape(2, 4)

ans1c = np.concatenate((m1,m2),axis = 0)
print(ans1c)
ans1v = np.vstack((m1,m2))
print(ans1v, '\n')

ans21, ans22 = np.hsplit(ans1c, 2)
print(ans21, '\n\n', ans22, '\n')

ans3 = np.tile(ans21, (1,2))
print(ans3)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]] 

[[0 1]
 [4 5]
 [0 1]
 [4 5]] 

 [[2 3]
 [6 7]
 [2 3]
 [6 7]] 

[[0 1 0 1]
 [4 5 4 5]
 [0 1 0 1]
 [4 5 4 5]]
