一个numpy array只含一种数据类型

In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [11]:
print(np.zeros((5)))
print(np.zeros((5)).shape)

[0. 0. 0. 0. 0.]
(5,)


In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [8]:
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Axis, rank(like dimention), shape, size and Data Type

In [13]:
np_array = np.zeros((3,4))
print(np_array.shape) 
print(np_array.ndim) # rank
print(np_array.size)

(3, 4)
2
12


In [17]:
int_array = np.array([1,2,3])
print(int_array.dtype)
print(int_array.itemsize)

float_array = np.array([1.,2.,3.])
print(float_array.dtype)
print(float_array.itemsize)

float32_array = np.array([1,2,3], dtype = np.float32)
print(float32_array.dtype)
print(float32_array.itemsize)

float128_array = np.array([1,2,3], dtype = np.float128)
print(float128_array.dtype)
print(float128_array.itemsize)

int64
8
float64
8
float32
4
float128
16


In [4]:
ary1 = np.full((2,3), 3)
ary2 = np.full(6, 6)
print(ary1)
print(ary1.ndim) 
print(ary2)
print(ary2.ndim)

[[3 3 3]
 [3 3 3]]
2
[6 6 6 6 6 6]
1


# np.reshape(), np.ravel()

In [33]:
x = np.reshape(ary1, (3,2))
x[0,0] = 1000
print(x)
print(ary1)

y = x.ravel()
y[0] = 2000
print(y)
print(x)
print(ary1)

[[1000    3]
 [   3    3]
 [   3    3]]
[[1000    3    3]
 [   3    3    3]]
[2000    3    3    3    3    3]
[[2000    3]
 [   3    3]
 [   3    3]]
[[2000    3    3]
 [   3    3    3]]


# copy()

In [34]:
npary1 = np.arange(4)
npary2 = npary1.copy()
npary2[0] = 2000
print(npary2, npary1)

[2000    1    2    3] [0 1 2 3]


# Arithmetic Operations (一对一)

In [35]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1//array2)
print(array1%array2)
print(array1**array2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0 0 0 0]
[1 2 3 4]
[    1    64  2187 65536]


# Random

In [39]:
print(np.random.random((3,3))) # 创建数值在0-1之间的随机数组
print(np.random.randint(100, size=(5))) # 创建5个数值范围在0-100间的随机整数
print(np.random.rand(3,4)) # 创建一个（3，4）的数值在0-1点矩阵
print(np.random.randn(10)) # 创建一个长度为10，数值范围能构成正态分布的数组

[[0.64230532 0.3207638  0.4847129 ]
 [0.55280017 0.13953237 0.42929326]
 [0.29947835 0.66217462 0.89917161]]
[68 65 84 28 63]
[[0.84184667 0.45904733 0.65199748 0.75886582]
 [0.26770565 0.04526921 0.15572596 0.74531184]
 [0.37055126 0.17231256 0.32307311 0.62992425]]
[ 0.30684206 -0.8843928  -0.93743522  2.48566201 -1.28618745  0.89929661
 -1.84782853  0.09079386  0.9272166   1.27183698]


# 单位矩阵（eye）

In [42]:
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 等差数组--添加步长/np.linspace()

In [45]:
print(np.arange(1,5))
print(np.arange(1.,5.))
print(np.arange(1,5,0.5))

[1 2 3 4]
[1. 2. 3. 4.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [47]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# fromfunction()

In [50]:
np.fromfunction(lambda i,j: i == j, (3,3), dtype = int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [49]:
np.fromfunction(lambda i,j: i+j, (3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [51]:
def my_func(x, y, z):
    return x*y+z
np.fromfunction(my_func, (3,2,7))

array([[[0., 1., 2., 3., 4., 5., 6.],
        [0., 1., 2., 3., 4., 5., 6.]],

       [[0., 1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6., 7.]],

       [[0., 1., 2., 3., 4., 5., 6.],
        [2., 3., 4., 5., 6., 7., 8.]]])