# 

In [3]:
import numpy as np

# Arithmetic operations

In [14]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.arange(5,9).reshape(2,2)

print(mat1)
print(mat2)

print(mat1 + mat2)
print(np.add(mat1, mat2))

print(mat1 - mat2)
print(np.subtract(mat1, mat2))

print(mat1 * mat2)
print(np.multiply(mat1, mat2))

print(mat1 / mat2)
print(np.divide(mat1, mat2))

print(mat1 // mat2)
print(np.floor_divide(mat1, mat2))

print(mat1 % mat2)
print(np.mod(mat1, mat2))

print(mat1 ** mat2)
print(np.power(mat1, mat2))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[    1    64]
 [ 2187 65536]]
[[    1    64]
 [ 2187 65536]]


# Mathematical and statistical functions

In [5]:
rand_matrix = (np.random.randint(10,1000,size=(2,5))-500) / 10.0
print(rand_matrix)
print(np.sign(rand_matrix))
print(np.nonzero(rand_matrix))
print(np.ceil(rand_matrix)) # 拿到大于元素的最小整数
print(np.cumsum(rand_matrix)) # 计算累计和
print(f'{np.diff(rand_matrix)} \n\n') # 计算相邻两数差

print(np.square(rand_matrix))
print(np.sqrt(rand_matrix))
print(f'{np.isnan(np.sqrt(rand_matrix))} \n\n')

print(np.sin(rand_matrix))
print(np.sort(rand_matrix))

[[-35.3  -9.7 -21.2  31.4 -37.7]
 [  2.8 -16.   -1.3  42.4  44. ]]
[[-1. -1. -1.  1. -1.]
 [ 1. -1. -1.  1.  1.]]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))
[[-35.  -9. -21.  32. -37.]
 [  3. -16.  -1.  43.  44.]]
[-35.3 -45.  -66.2 -34.8 -72.5 -69.7 -85.7 -87.  -44.6  -0.6]
[[ 25.6 -11.5  52.6 -69.1]
 [-18.8  14.7  43.7   1.6]] 


[[1.24609e+03 9.40900e+01 4.49440e+02 9.85960e+02 1.42129e+03]
 [7.84000e+00 2.56000e+02 1.69000e+00 1.79776e+03 1.93600e+03]]
[[       nan        nan        nan 5.60357029        nan]
 [1.67332005        nan        nan 6.51152824 6.63324958]]
[[ True  True  True False  True]
 [False  True  True False False]] 


[[ 6.76117835e-01  2.71760626e-01 -7.11161223e-01 -1.59258626e-02
  -8.88156806e-04]
 [ 3.34988150e-01  2.87903317e-01 -9.63558185e-01 -9.99933866e-01
   1.77019251e-02]]
[[-37.7 -35.3 -21.2  -9.7  31.4]
 [-16.   -1.3   2.8  42.4  44. ]]


/var/folders/_d/ygp6b6291jq_99s9fqh98qv40000gn/T/ipykernel_48114/268745472.py:10: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(rand_matrix))
/var/folders/_d/ygp6b6291jq_99s9fqh98qv40000gn/T/ipykernel_48114/268745472.py:11: RuntimeWarning: invalid value encountered in sqrt
  print(f'{np.isnan(np.sqrt(rand_matrix))} \n\n')


In [33]:
# 常用统计函数
print(mat1, '\n')

print(mat1.mean())
print(np.mean(mat1))
print(np.median(mat1),'\n')

print(np.max(mat1))
print(np.argmax(mat1))
print(np.min(mat1))
print(np.argmin(mat1),'\n')

print(np.sum(mat1))
print(np.sum(mat1, axis=0)) # 按列求和
print(np.sum(mat1, axis=1),'\n') # 按行求和

print(np.abs(mat1),'\n')


[[1 2]
 [3 4]] 

2.5
2.5
2.5 

4
3
1
0 

10
[4 6]
[3 7] 

[[1 2]
 [3 4]] 



# Linear Algebra

转置

In [35]:
mat = np.arange(3)
print(mat)
print(mat.T )
mat = mat.reshape(1,3)
print(mat)
print(mat.T )

[0 1 2]
[0 1 2]
[[0 1 2]]
[[0]
 [1]
 [2]]


In [43]:
print(mat1)
print(mat2)
print(mat1*mat2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 5 12]
 [21 32]]


点乘

In [39]:
print(mat1.dot(mat2))

[[19 22]
 [43 50]]


行列式：

In [40]:
print(np.linalg.det(mat1))

-2.0000000000000004


逆矩阵

In [37]:
try: 
    print(np.linalg.inv(mat1))
except:
    print('error')

[[-2.   1. ]
 [ 1.5 -0.5]]


特征值，特征向量

In [47]:
eigen_val, eigen_vec = np.linalg.eig(mat1)
print(eigen_val, '\n', eigen_vec)
print(mat1.dot(eigen_vec) - eigen_val*eigen_vec)

[-0.37228132  5.37228132] 
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[[ 0.00000000e+00 -4.44089210e-16]
 [ 5.55111512e-17  0.00000000e+00]]


解线性方程组

In [49]:
coeff = np.array([[2,6],[5,3]])
depvar = np.array([6,-9])
solution = np.linalg.solve(coeff, depvar)
print(solution)
coeff.dot(solution), depvar

[-3.  2.]


(array([ 6., -9.]), array([ 6, -9]))

Exercise

In [50]:
matrix1 = np.arange(15).reshape(3, 5)
matrix2 = np.arange(15).reshape(5, 3)

In [52]:
result = matrix1.dot(matrix2) # or np.dot(matrix1, matrix2)
print(result)
sqrt = np.sqrt(result)
print(sqrt)
totsum = np.sum(sqrt)
print(totsum)
stepsum = np.cumsum(sqrt)
print(stepsum)

[[ 90 100 110]
 [240 275 310]
 [390 450 510]]
[[ 9.48683298 10.         10.48808848]
 [15.49193338 16.58312395 17.60681686]
 [19.74841766 21.21320344 22.58317958]]
143.2015963354727
[  9.48683298  19.48683298  29.97492146  45.46685485  62.0499788
  79.65679566  99.40521332 120.61841675 143.20159634]
