In [1]:
import numpy as np

# 一维数组索引

In [6]:
npary = np.arange(10)

print(npary)
print(npary[2:6])
print(npary[:7])
print(npary[3:])
print(npary[:-3])
print(npary[2:-3])
print(npary[::-1])
print(npary[2:9:3])
print(npary[-1:5:-2])
print(npary[-1:3:-2])
print(npary[-1:7:-2])
print(npary[-1:5:-2])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[0 1 2 3 4 5 6]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[2 3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]
[2 5 8]
[9 7]
[9 7 5]
[9]
